name: Create Repository Dispatch
on: push
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dispatch
        uses: ./
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          repositories: |
            vcpsuthakar/repositories-dispatch-demo
          event_type: test_dispatch
          client_payload: '{"github": ${{ toJson(github) }}}'
