name: Create Repository Dispatch
on: 
 workflow_dispatch:
 workflow_run:
    workflows: ["common-repo.yml"]
    types:
      - completed

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Dispatch
        id: dispatch
        uses: ./
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          repositories: |
            vcpsuthakar/common
          event_type: test_dispatch
          client_payload: '{"github": ${{ toJson(github) }}}'

  wait-for-target:
    runs-on: ubuntu-latest
    needs: dispatcher
    steps:
      - name: Wait for Target Workflow to Complete
        id: wait-for-target
        run: |
          TARGET_WORKFLOW="vcpsuthakar/common/common-repo.yml.yml"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          while true; do
            STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/$TARGET_WORKFLOW/actions/runs" | jq -r '.workflow_runs[0].status')
            
            if [ "$STATUS" == "completed" ]; then
              break
            elif [ "$STATUS" == "failure" ]; then
              echo "Target workflow failed. Aborting."
              exit 1
            elif [ "$STATUS" == "cancelled" ]; then
              echo "Target workflow was cancelled. Aborting."
              exit 1
            fi
            sleep 10 
          done
          echo "Target workflow has completed successfully."

      - name: Set Output
        run: echo "::set-output name=target_status::completed"

      - name: Set Output
        run: echo "::set-output name=target_status::completed"
  build:
    runs-on: ubuntu-latest
    needs: wait-for-target    
    steps:
     - name: Checkout Microservice Repo
       uses: actions/checkout@v2
