name: Create Repository Dispatch
on: workflow_dispatch

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
      - uses: ./
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          repositories: |
            vcpsuthakar/common
          event_type: test_dispatch
          client_payload: '{"github": ${{ toJson(github) }}}'

  build:
    runs-on: ubuntu-latest
    needs: dispatcher
    steps:
      - name: Checkout Microservice Repo
        uses: actions/checkout@v2
