name: Create Repository Dispatch
on: workflow_dispatch

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    outputs:
      dispatch-successful: ${{ steps.dispatch.outputs.success }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Dispatch
        id: dispatch
        uses: ./
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          repositories: |
            vcpsuthakar/common
          event_type: test_dispatch
          client_payload: '{"github": ${{ toJson(github) }}}'

  build:
    runs-on: ubuntu-latest
    needs: dispatcher
    if: ${{ needs.dispatcher.outputs.dispatch-successful == 'true' }}
    steps:
      - name: Checkout Microservice Repo
        uses: actions/checkout@v2

      # Add your build steps here
