name: Microservice Main Workflow

on:
  push:
    branches:
      - master

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Common Workflow
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: vcpsuthakar/common 
          event-type: trigger-workflow-event 

  #    - name: Wait for Repo B Workflow Completion
  #      id: wait-for-workflow
  #      uses: octokit/request-action@v2.x
  #      with:
  #        route: POST /repos/vcpsuthakar/common/actions/runs
  #        token: ${{ secrets.GITHUB_TOKEN }}
  #        event_type: trigger-workflow-event

      - name: Check Workflow Status
        run: |
          if [[ "${{ steps.wait-for-workflow.outputs.status }}" == "completed" && "${{ steps.wait-for-workflow.outputs.conclusion }}" == "success" ]]; then
            echo "Repo B workflow completed successfully."
          else
            echo "Repo B workflow failed or is still running."
            exit 1
          fi
