name: Create Repository Dispatch
on: 
 workflow_dispatch:
 workflow_run:
    workflows: ["common-repo.yml"]
    types:
      - completed

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Dispatch
        id: dispatch
        uses: ./
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          repositories: |
            vcpsuthakar/common
          event_type: test_dispatch
          client_payload: '{"github": ${{ toJson(github) }}}'

  wait-for-target:
    runs-on: ubuntu-latest
    needs: dispatcher
    steps:
      - name: Wait for Target Workflow to Complete
        id: wait-for-target
        run: |
          target_workflow_status="in_progress"
          while [ "$target_workflow_status" != "completed" ]; do
            sleep 5 
            target_workflow_status=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/vcpsuthakar/common/actions/workflows/common-repo.yml/runs?event=workflow_run" \
              | jq -r '.workflow_runs[0].status')
              echo "$target_workflow_status"
          done
          echo "Target workflow has completed successfully."

      - name: Set Output
        run: echo "::set-output name=target_status::completed"
  build:
    runs-on: ubuntu-latest
    needs: wait-for-target    
    steps:
     - name: Checkout Microservice Repo
       uses: actions/checkout@v2
