name: Test Dispatch
on: workflow_dispatch

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          # token: ${{ secrets.REPO_TOKEN }}
          event-type: mytests
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
