name: Get Common Workflow Status

on:
  workflow_run:
    workflows: ["Common Workflow"]
    types:
      - completed

jobs:
  get-common-workflow-status:
    runs-on: ubuntu-latest

    steps:
      - name: Get Common Workflow Status
        id: common-status
        run: |
          repo_owner="vcpsuthakar"
          repo_name="common"
          workflow_name="Common Workflow"

          # Get the latest run of the Common Workflow
          response=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${repo_owner}/${repo_name}/actions/workflows/${workflow_name}/runs?event=trigger-common")

          # Extract the run ID and status
          run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
          status=$(echo "$response" | jq -r '.workflow_runs[0].conclusion')

          echo "Common Workflow Run ID: $run_id"
          echo "Common Workflow Status: $status"
          
          # You can perform additional actions based on the status here

