name: Trigger Second Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Second Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Second Workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          run: |
              curl -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.everest-preview+json" \
                -d '{"event_type": "second-workflow-trigger", "client_payload": {"key1": "value1", "key2": "value2"}}' \
                "https://api.github.com/repos/vcpsuthakar/common/dispatches"
